version: '3'
services:
# used docker first uncommet stramlit links
  web: 
    build: ./
    image: fl
    ports:
      - "8080:8080"
    # volumes:
    #   - $PWD/data:/var/lib/mysql
    # container_name: FASTAPIFACE
    networks:
      - frontend
                                                
  streamlit:
    build: STREAMLIT/
    image: st
    depends_on:
      - web
    ports:
      - "8501:8501"
    # volumes:
    #   - $PWD/data:/var/lib/mysql
    networks:
      - frontend

networks:
  frontend:
    driver: bridge